name: Upload Standalone Version to Itch.ip

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodule
      run: git submodule init && git submodule update
    - run: npm ci
    - run: npm run package
    - run: node .github/scripts/upload-itch.js
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}