name: Upload Standalone Version to Itch.ip

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Wine
      run: brew cask install wine-stable
    - name: Checkout submodule
      run: git submodule init && git submodule update
    - run: npm ci
    - run: npm run package
    - run: bash .github/scripts/upload.sh
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}